assemble_app/config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  resources :technologies
  resources :projects
  get '/members' => 'member#index'
  post 'members' => 'member#create'
  devise_for :users
  get '/project_technologies' => 'project_technology#index'
  # Chat routes
  # get '/rooms' => 'rooms#index'
  # get '/rooms/:id' => 'rooms#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # this will help us differentiate between HTML and JSON requests, so that whenever we get HTML requests it'll lead us to our index and if we make a JSON request it'll go to the backend.
  get '*path', to: 'home#index', constraints: -> (request) {request.format.html?}
  # defaults our homepage to our index view through the home controller
  root to: "home#index"
end

assemble_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

assemble_app/app/models/member.rb
class Member < ApplicationRecord
    belongs_to :user
    belongs_to :project
end

assemble_app/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room, inverse_of: :messages
end

assemble_app/app/models/project.rb
class Project < ApplicationRecord
    has_many :members
    has_many :users, through: :members
    has_many :project_technologies
    has_many :technologies, through: :project_technologies
end

assemble_app/app/models/project_technology.rb
class ProjectTechnology < ApplicationRecord
    belongs_to :technology, required: false
    belongs_to :project, required: false
end

assemble_app/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy, inverse_of: :room
end

assemble_app/app/models/technology.rb
class Technology < ApplicationRecord
    has_many :project_technologies
    has_many :projects, through: :project_technologies
    has_many :user_technologies
    has_many :users, through: :user_technologies
end

assemble_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true

  has_many :members
  has_many :projects, through: :members
  has_many :user_technologies
  has_many :technologies, through: :user_technologies
end

assemble_app/app/models/user_technology.rb
class UserTechnology < ApplicationRecord
    belongs_to :technology 
    belongs_to :user
end

assemble_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
    end
end

assemble_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

assemble_app/app/controllers/member_controller.rb
class MemberController < ApplicationController
    def index
        members = Member.all
        render json: members
    end   
    
    def create
        member = Member.create(member_params)
        if project.valid?
            render json: project
        else
            render json: project.errors, status: :unprocessable_entity
        end
    end

    private
    def member_params
        params.require(:project).permit(:user_id, :project_id, :is_owner)
    end
end

assemble_app/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :load_entities
    def create        
        @message = Message.create user: current_user, room: @room, content: params.dig(:message, :content)   
    end

    protected
    def load_entities        
        @room = Room.find params.dig(:message, :room_id)    
    end
    
end

assemble_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    
    def index
        projects = Project.all
        render json: projects
    end
    
    def create
        project = Project.create(project_params["project"])
        if project.valid?
            Member.create(user_id: current_user.id, project_id: project.id, is_owner: true)
            project_params["projectTechnologies"].each do |attribute| 
                ProjectTechnology.create(project_id: project.id, technology_id: attribute)
            end

            render json: project
        else
            render json: project.errors, status: :unprocessable_entity
        end
        
        
    end

    def update
        project = Project.find(params[:id])
        project.update(project_params)
        if project.valid?
            render json: project
        else
            render json: project.errors
        end
    end

    def destroy
        project = Project.find(params[:id])
        project.destroy
        if project.valid?
            render json: project
        else
            render json: project.errors
        end
    end

    private
    def project_params
        params.permit(:project =>[:name, :description], :projectTechnologies => [])
    end
end

assemble_app/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    # Loads:  
    # @rooms = all rooms  
    # @room = current room when applicable  
    
    before_action :load_entities
    
    def index    
        @rooms = Room.all  
    end
    def new    
        @room = Room.new  
    end
    def create   
         @room = Room.new permitted_parameters
        if @room.save      
            flash[:success] = "Room #{@room.name} was created successfully"      
            redirect_to rooms_path    
        else      
            render :new    
        end  
    end
    def edit  
    end
    def update    
        if @room.update_attributes(permitted_parameters)      
            flash[:success] = "Room #{@room.name} was updated successfully"      
            redirect_to rooms_path    
        else      
            render :new    
        end  
    end
    def show    
        @message = Message.new room: @room    
        @messages = @room.messages.includes(:user)  
    end
    
    protected
    def load_entities   
        @rooms = Room.all   
        @room = Room.find(params[:id]) if params[:id]  
    end
    
    def permitted_parameters   
         params.require(:room).permit(:name)  
    end
end

assemble_app/app/helpers/application_helper.rb
module ApplicationHelper
end

assemble_app/app/helpers/home_helper.rb
module HomeHelper
end

assemble_app/app/helpers/member_helper.rb
module MemberHelper
end

assemble_app/app/helpers/messages_helper.rb
module MessagesHelper
end

assemble_app/app/helpers/project_technology_helper.rb
module ProjectTechnologyHelper
end

assemble_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

assemble_app/app/helpers/rooms_helper.rb
module RoomsHelper
end

assemble_app/app/helpers/technologies_helper.rb
module TechnologiesHelper
end

assemble_app/app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
    <%= form.input :name %>
    <%= form.submit "Save", class: 'btn btn-success' %>
<% end %>

assemble_app/app/views/rooms/_rooms.html.erb
<div class="mb-3">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Create a room
  <% end %>
</div>

<% if @rooms.present? %>
  <nav class="nav flex-column">
    <% @rooms.each do |room| %>
      <%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
    <% end %>
  </nav>
<% else %>
  <div class="text-muted">
    The are no rooms
  </div>
<% end %>

assemble_app/app/views/rooms/edit.html.erb
<h3> Editing <%= @room.name %> </h3>

<%= render partial: 'form' %>

assemble_app/app/views/rooms/index.html.erb
<%= render partial: 'shared/navigation_bar' %>
<div class="container">
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>
  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the Assemble Chatrooms!
      </h4>

      <p>
        Utilize this messenger to communicate with your team members.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
  </div>
</div>
</div>

assemble_app/app/views/rooms/new.html.erb
<h3> Create a Room </h3>

<%= render partial: 'form' %>

assemble_app/app/views/rooms/show.html.erb
<%= render partial: 'shared/navigation_bar' %>
<h3>
  <%= @room.name %>
</h3>

<div class="container">
<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'rooms' %>
  </div>

 <div class="col">
    <div class="chat" style="border: 1px solid gray; border-radius: 5px 5px 0 0; background-color: gray; height: 50vh; overflow-y: auto;">
      <% @messages.each do |message| %>
        <div class="chat-message-container">
          <div class="row no-gutters">
            <div class="col-auto text-center">
              <%= message.user.username %>:
            </div>

            <div class="col">
              <div class="message-content">
                <p class="mb-1">
                  <%= message.content %>
                </p>

                <div class="text-right">
                  <small>
                    <%= message.created_at %>
                  </small>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
</div>

    <%= simple_form_for @message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :content, as: :string,
            wrapper: false,
            label: false,
            input_html: {
            class: 'chat-input'
            } 
        %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-primary chat-input' %>
        </div>
      </div>

      <%= form.input :room_id, as: :hidden %>
    <% end %>
  </div>
</div>
</div>